import configData from "../config.json";
import type { SiteConfig, ProfileConfig, LinkConfig, Project, Skill, TechItem, Language, I18nText, GuestbookConfig, FriendLinksConfig } from "../types";

interface AppConfig {
  site: SiteConfig;
  profile: ProfileConfig;
  links: Record<string, LinkConfig>;
  projects: {
    featured: Project[];
    moreProjectsUrl: string;
  };
  skills: Skill[];
  techStack: {
    backend: TechItem[];
    mobile: TechItem[];
    frontend: TechItem[];
  };
  translations: {
    zh: Record<string, string>;
    en: Record<string, string>;
  };
  guestbook?: GuestbookConfig;
  friendLinks?: FriendLinksConfig;
}

const appConfig: AppConfig = configData as AppConfig;

export const linksConfig = appConfig.links;

export const projectsConfig: Project[] = appConfig.projects.featured;

export const moreProjectsConfig = {
  url: appConfig.projects.moreProjectsUrl,
  title: {
    zh: appConfig.translations.zh.moreProjects || "查看更多项目",
    en: appConfig.translations.en.moreProjects || "View More Projects",
  },
};

export const skillsConfig: Skill[] = appConfig.skills;

export const socialConfig = {
  email: {
    url: appConfig.links.email?.url || "",
    icon: appConfig.links.email?.icon || "fas fa-envelope",
    color: "from-blue-400 to-blue-600",
  },
};

export const techStackConfig = {
  backend: appConfig.techStack.backend as TechItem[],
  mobile: appConfig.techStack.mobile as TechItem[],
  frontend: appConfig.techStack.frontend as TechItem[],
};

export const aboutMeConfig = {
  name: appConfig.profile.name,
  location: appConfig.profile.location,
  focus: appConfig.profile.focus,
  hobbies: appConfig.profile.hobbies,
  currentFocus: appConfig.profile.currentFocus,
  motto: appConfig.profile.motto,
};

export const guestbookConfig = appConfig.guestbook || {
  enabled: false,
  walineUrl: "",
  title: { zh: "留言板", en: "Guestbook" }
};

export const friendLinksConfig = appConfig.friendLinks || {
  enabled: false,
  title: { zh: "友链", en: "Friend Links" },
  links: []
};

export const translations = {
  zh: {
    siteTitle: appConfig.translations.zh.siteTitle || appConfig.site.title,
    typeWriterText: appConfig.profile.typeWriterTexts.zh[0],
    typeWriterText2: appConfig.profile.typeWriterTexts.zh[1],
    quickLinks: appConfig.translations.zh.quickLinks,
    footer: appConfig.site.footer.zh,
    nav: {
      blog: appConfig.links.blog?.title.zh || "Blog",
      github: appConfig.links.github?.title.zh || "GitHub",
      gitee: appConfig.links.gitee?.title.zh || "Gitee",
    },
    aboutMe: appConfig.translations.zh.aboutMe,
    techStack: appConfig.translations.zh.techStack,
    backend: appConfig.translations.zh.backend,
    mobile: appConfig.translations.zh.mobile,
    frontend: appConfig.translations.zh.frontend,
    currentFocus: appConfig.translations.zh.currentFocus,
    featuredProjects: appConfig.translations.zh.featuredProjects,
    skills: appConfig.translations.zh.skills,
    viewProject: appConfig.translations.zh.viewProject,
    moreProjects: appConfig.translations.zh.moreProjects,
    totalMusic: (count: number) => `共 ${count} 首`,
    openMusicPlayer: "打开音乐播放器",
    listLoop: "列表循环",
    listNoLoop: "列表不循环",
    singleLoop: "单曲循环",
    singleNoLoop: "单曲不循环",
    noMusicSelected: "未选择音乐",
    cancelMute: "取消静音",
    mute: "静音",
    playlist: "播放列表",
    switchToEnglish: "Switch to English",
    switchToChinese: "切换到中文",
    switchToLightMode: "切换到亮色模式",
    switchToDarkMode: "切换到暗色模式",
    configManagement: "配置管理",
    locationLoading: "定位中...",
    locationDenied: "位置未授权",
    cursorSettings: "鼠标指针设置",
    siteComponents: "网站组件",
    localTimeComponent: "时间组件",
    enableLocalTime: "启用时间组件",
    customCursor: "自定义鼠标指针",
    enableCustomCursor: "启用自定义鼠标指针",
    cursorFile: "指针文件",
    cursorFileHint: "仅支持 .cur 格式的鼠标指针文件",
    cursorFileError: "请上传 .cur 格式的文件",
    cursorUploadSuccess: "指针文件上传成功",
    cursorUploadError: "指针文件上传失败",
    resetCursor: "重置为默认",
    cursorPreviewHint: "将鼠标移到此处预览效果",
    expandAll: "展开全部",
    collapseAll: "收起全部",
    quickNav: "快速导航",
    clear: "清除",
    backToHome: "返回主页",
    configDescription: "通过可视化界面管理您的个人主页配置，所有修改将同步到 GitHub",
    githubAuth: "GitHub App 认证",
    pemKeyFile: "PEM 密钥文件",
    pemKeyHint: "从 GitHub App 设置页面下载的 .pem 私钥文件",
    pemKeyLoaded: "已加载 PEM 密钥",
    siteInfo: "网站信息",
    siteName: "网站名称",
    siteTitleLabel: "网站标题",
    siteUrl: "网站 URL",
    footerSettings: "页脚设置",
    footerText: "页脚文本",
    author: "作者",
    siteDescription: "网站描述",
    keywords: "关键词",
    backgroundImage: "背景图",
    darkTheme: "暗色主题",
    lightTheme: "亮色主题",
    textColor: "主文字颜色",
    textSecondaryColor: "次要文字颜色",
    profile: "个人资料",
    name: "姓名",
    avatar: "头像",
    location: "位置",
    focus: "专注领域",
    hobbies: "爱好",
    motto: "座右铭",
    typeWriterText1Label: "打字机文本 1",
    typeWriterText2Label: "打字机文本 2",
    links: "链接管理",
    linkUrl: "链接地址",
    linkTitle: "标题",
    linkDescription: "描述",
    linkIcon: "图标",
    showLink: "显示",
    skillColor: "渐变色",
    skillIcon: "图标",
    retry: "重试",
    uploadPemFirst: "请先上传 GitHub App PEM 密钥",
    fileUploadSuccess: "文件上传成功",
    fileUploadFailed: "文件上传失败，请重试",
    configSaveSuccess: "配置保存成功！已提交到 GitHub",
    configSaveFailed: "保存配置失败，请检查网络连接和密钥配置",
    loadConfigFailed: "加载配置失败",
    saveToGithub: "保存配置并提交到 GitHub",
    saving: "保存中...",
    addProject: "添加项目",
    projectName: "项目名称",
    projectUrl: "项目链接",
    projectImage: "项目图片",
    projectIcon: "项目图标",
    projectGradient: "渐变色",
    projectDescription: "项目描述",
    projectTags: "标签（逗号分隔）",
    delete: "删除",
    description: "描述",
    chinese: "中文",
    english: "English",
    addSkill: "添加技能",
    level: "等级",
    icon: "图标",
    uploadMusic: "上传音乐",
    musicUploadHint: "上传的音乐将保存到 public/music 目录，支持 MP3、WAV、OGG、M4A、FLAC 格式，最大 20MB",
    noMusic: "暂无音乐，点击上方按钮上传",
    loading: "加载中...",
    weekdays: ["周日", "周一", "周二", "周三", "周四", "周五", "周六"],
    months: ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"],
    guestbook: appConfig.translations.zh.guestbook || "留言板",
    friendLinks: appConfig.translations.zh.friendLinks || "友链",
    visitSite: appConfig.translations.zh.visitSite || "访问网站",
    noFriendLinks: appConfig.translations.zh.noFriendLinks || "暂无友链",
    addFriendLink: appConfig.translations.zh.addFriendLink || "添加友链",
    friendLinkUrl: appConfig.translations.zh.friendLinkUrl || "网站地址",
    friendLinkName: appConfig.translations.zh.friendLinkName || "网站名称",
    friendLinkAvatar: appConfig.translations.zh.friendLinkAvatar || "网站图标",
    friendLinkDescription: appConfig.translations.zh.friendLinkDescription || "网站描述",
    fetchSiteInfo: appConfig.translations.zh.fetchSiteInfo || "获取网站信息",
    fetchingSiteInfo: appConfig.translations.zh.fetchingSiteInfo || "正在获取网站信息...",
    fetchSiteInfoSuccess: appConfig.translations.zh.fetchSiteInfoSuccess || "网站信息获取成功",
    fetchSiteInfoFailed: appConfig.translations.zh.fetchSiteInfoFailed || "网站信息获取失败，请手动填写",
    guestbookSettings: "留言板设置",
    enableGuestbook: "启用留言板",
    walineUrl: "Waline 服务端地址",
    walineUrlHint: "填写 Waline 评论系统的服务端地址",
    walineNick: "昵称",
    walineMail: "邮箱",
    walinePlaceholder: "欢迎留下你的评论...",
    walineNickPlaceholder: "请输入昵称",
    walineMailPlaceholder: "请输入邮箱",
    friendLinksSettings: "友链设置",
    enableFriendLinks: "启用友链",
    sidebarCollapse: "收起导航",
    sidebarExpand: "展开导航",
  },
  en: {
    siteTitle: appConfig.translations.en.siteTitle || appConfig.site.title,
    typeWriterText: appConfig.profile.typeWriterTexts.en[0],
    typeWriterText2: appConfig.profile.typeWriterTexts.en[1],
    quickLinks: appConfig.translations.en.quickLinks,
    footer: appConfig.site.footer.en,
    nav: {
      blog: appConfig.links.blog?.title.en || "Blog",
      github: appConfig.links.github?.title.en || "GitHub",
      gitee: appConfig.links.gitee?.title.en || "Gitee",
    },
    aboutMe: appConfig.translations.en.aboutMe,
    techStack: appConfig.translations.en.techStack,
    backend: appConfig.translations.en.backend,
    mobile: appConfig.translations.en.mobile,
    frontend: appConfig.translations.en.frontend,
    currentFocus: appConfig.translations.en.currentFocus,
    featuredProjects: appConfig.translations.en.featuredProjects,
    skills: appConfig.translations.en.skills,
    viewProject: appConfig.translations.en.viewProject,
    moreProjects: appConfig.translations.en.moreProjects,
    totalMusic: (count: number) => `${count} songs`,
    openMusicPlayer: "Open music player",
    listLoop: "List loop",
    listNoLoop: "List no loop",
    singleLoop: "Single loop",
    singleNoLoop: "Single no loop",
    noMusicSelected: "No music selected",
    cancelMute: "Unmute",
    mute: "Mute",
    playlist: "Playlist",
    switchToEnglish: "Switch to English",
    switchToChinese: "切换到中文",
    switchToLightMode: "Switch to light mode",
    switchToDarkMode: "Switch to dark mode",
    configManagement: "Config Management",
    locationLoading: "Locating...",
    locationDenied: "Location denied",
    cursorSettings: "Cursor Settings",
    siteComponents: "Site Components",
    localTimeComponent: "Local Time Component",
    enableLocalTime: "Enable Local Time",
    customCursor: "Custom Cursor",
    enableCustomCursor: "Enable custom cursor",
    cursorFile: "Cursor File",
    cursorFileHint: "Only .cur format cursor files are supported",
    cursorFileError: "Please upload a .cur file",
    cursorUploadSuccess: "Cursor file uploaded successfully",
    cursorUploadError: "Cursor file upload failed",
    resetCursor: "Reset to default",
    cursorPreviewHint: "Hover here to preview",
    expandAll: "Expand All",
    collapseAll: "Collapse All",
    quickNav: "Quick Navigation",
    clear: "Clear",
    backToHome: "Back to Home",
    configDescription: "Manage your personal homepage configuration through a visual interface, all changes will be synced to GitHub",
    githubAuth: "GitHub App Authentication",
    pemKeyFile: "PEM Key File",
    pemKeyHint: "The .pem private key file downloaded from GitHub App settings",
    pemKeyLoaded: "PEM key loaded",
    siteInfo: "Site Information",
    siteName: "Site Name",
    siteTitleLabel: "Site Title",
    siteUrl: "Site URL",
    footerSettings: "Footer Settings",
    footerText: "Footer Text",
    author: "Author",
    siteDescription: "Site Description",
    keywords: "Keywords",
    backgroundImage: "Background Image",
    darkTheme: "Dark Theme",
    lightTheme: "Light Theme",
    textColor: "Primary Text Color",
    textSecondaryColor: "Secondary Text Color",
    profile: "Profile",
    name: "Name",
    avatar: "Avatar",
    location: "Location",
    focus: "Focus",
    hobbies: "Hobbies",
    motto: "Motto",
    typeWriterText1Label: "TypeWriter Text 1",
    typeWriterText2Label: "TypeWriter Text 2",
    links: "Links",
    linkUrl: "URL",
    linkTitle: "Title",
    linkDescription: "Description",
    linkIcon: "Icon",
    showLink: "Show",
    skillColor: "Gradient",
    skillIcon: "Icon",
    retry: "Retry",
    uploadPemFirst: "Please upload GitHub App PEM key first",
    fileUploadSuccess: "File uploaded successfully",
    fileUploadFailed: "File upload failed, please try again",
    configSaveSuccess: "Configuration saved! Committed to GitHub",
    configSaveFailed: "Failed to save configuration, please check network and key settings",
    loadConfigFailed: "Failed to load configuration",
    saveToGithub: "Save Configuration and Commit to GitHub",
    saving: "Saving...",
    addProject: "Add Project",
    projectName: "Project Name",
    projectUrl: "Project URL",
    projectImage: "Project Image",
    projectIcon: "Project Icon",
    projectGradient: "Gradient",
    projectDescription: "Description",
    projectTags: "Tags (comma separated)",
    delete: "Delete",
    description: "Description",
    chinese: "Chinese",
    english: "English",
    addSkill: "Add Skill",
    level: "Level",
    icon: "Icon",
    uploadMusic: "Upload Music",
    musicUploadHint: "Music will be saved to public/music directory, supports MP3, WAV, OGG, M4A, FLAC formats, max 20MB",
    noMusic: "No music yet, click the button above to upload",
    loading: "Loading...",
    weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    guestbook: appConfig.translations.en.guestbook || "Guestbook",
    friendLinks: appConfig.translations.en.friendLinks || "Friend Links",
    visitSite: appConfig.translations.en.visitSite || "Visit Site",
    noFriendLinks: appConfig.translations.en.noFriendLinks || "No friend links yet",
    addFriendLink: appConfig.translations.en.addFriendLink || "Add Friend Link",
    friendLinkUrl: appConfig.translations.en.friendLinkUrl || "Website URL",
    friendLinkName: appConfig.translations.en.friendLinkName || "Website Name",
    friendLinkAvatar: appConfig.translations.en.friendLinkAvatar || "Website Icon",
    friendLinkDescription: appConfig.translations.en.friendLinkDescription || "Website Description",
    fetchSiteInfo: appConfig.translations.en.fetchSiteInfo || "Fetch Site Info",
    fetchingSiteInfo: appConfig.translations.en.fetchingSiteInfo || "Fetching site info...",
    fetchSiteInfoSuccess: appConfig.translations.en.fetchSiteInfoSuccess || "Site info fetched successfully",
    fetchSiteInfoFailed: appConfig.translations.en.fetchSiteInfoFailed || "Failed to fetch site info, please fill manually",
    guestbookSettings: "Guestbook Settings",
    enableGuestbook: "Enable Guestbook",
    walineUrl: "Waline Server URL",
    walineUrlHint: "Enter the Waline comment system server URL",
    walineNick: "Nickname",
    walineMail: "Email",
    walinePlaceholder: "Leave your comment here...",
    walineNickPlaceholder: "Enter your nickname",
    walineMailPlaceholder: "Enter your email",
    friendLinksSettings: "Friend Links Settings",
    enableFriendLinks: "Enable Friend Links",
    sidebarCollapse: "Collapse Sidebar",
    sidebarExpand: "Expand Sidebar",
  },
};

export const siteConfig = appConfig.site;
export type { Language, I18nText };
